apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-deployment
spec:
  selector:
    matchLabels:
      app: playwright
  replicas: 1
  template:
    metadata:
      labels:
        app: playwright
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
