name: Playwright-Test
"on":
  push:
    branches:
      - main
jobs:
  Playwright-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: install dependencies
        run: npm install

      - name: Run type checks
        run: npx tsc -p tsconfig.json --noEmit

      - name: Playwright-run
        run: npm test
