name: Playwright Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run the tests
        run: npx playwright test
